name: CI/CD Pipeline
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install & Test
        run: |
          cd backend && npm ci && npm test
          cd ../frontend && npm ci && npm test

      - name: Build Docker Images
        run: |
          docker build -t ${{ secrets.REGISTRY }}/backend:latest ./backend
          docker build -t ${{ secrets.REGISTRY }}/frontend:latest ./frontend

      - name: Push to Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker push ${{ secrets.REGISTRY }}/backend:latest
          docker push ${{ secrets.REGISTRY }}/frontend:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/